apiVersion: apps/v1
kind: Deployment
metadata:
  name: choropleth-deployment
  labels:
    app: choropleth
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: choropleth
  template:
    metadata:
      labels:
        app: choropleth
    spec:
      containers:
      - name: choropleth
        image: bstefansenlbre/choropleth:latest 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: choropleth-service
spec:
  type: NodePort
  selector:
    app: choropleth
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 3000
      nodePort: 30100
